Update docker-compose

diff --git a/bin/docker-compose b/bin/docker-compose
--- a/bin/docker-compose
+++ b/bin/docker-compose
@@ -28,11 +28,11 @@ function __main__() {
   local REDIS_HOST="redis"
   local REDIS_PORT="6379"
 
-  if [[ ! "$SHARELATEX_IMAGE_VERSION" \
-          =~ ^[0-9]+\.[0-9]+\.[0-9]+(-RC)?$ ]]; then
-    echo "ERROR: invalid version '${SHARELATEX_IMAGE_VERSION}'"
-    exit 1
-  fi
+  # if [[ ! "$SHARELATEX_IMAGE_VERSION" \
+  #        =~ ^[0-9]+\.[0-9]+\.[0-9]+(-RC)?$ ]]; then
+  #   echo "ERROR: invalid version '${SHARELATEX_IMAGE_VERSION}'"
+  #   exit 1
+  # fi
 
   # Load vars from the rc file
   # shellcheck disable=SC1090
@@ -62,7 +62,7 @@ function __main__() {
   # Build up the flags to pass to docker-compose
   local project_name="${PROJECT_NAME:-overleaf}"
 
-  local image_name="sharelatex/sharelatex"
+  local image_name="hideojoho/sharelatex"
   if [[ "${SERVER_PRO:-null}" == "true" ]]; then
     image_name="quay.io/sharelatex/sharelatex-pro"
   fi
